# Site settings
title: Polipixel
email: hola@polipixel.com
slogan: Queremos construir algo increíble contigo
description: >-
  Somos un grupo de profesionales dedicados al desarrollo de software y
  diseño de interfaces aplicados a sitios web y aplicaciones móviles.
baseurl: ""
url: "https://polipixel.com"
copyright: 2019
facebook_username: polipixel.studio
twitter_username: polipixelstudio
linkedin_username: polipixel
github_username: polipixel

markdown: kramdown
permalink: /blog/:title:output_ext

feed:
  path: atom.xml

# Build settings
plugins:
  - jekyll-feed
  - breakpoint

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
   - LICENSE
   - README.md
   - extra
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
